fn main() {
    const table: [i32] = [10;0];
	var i = 0;
	while (i < 10) {
		print_i32(table[i]);
		print_string(" ");
		i += 1;
	}
	print_string("\n");
	
	var multi_table: [[i32]] = [10;[5;0]];
	var x = 0;
	var y = 0;
	for (row in multi_table) {
        for (v in iter_i32(&row)) {
			x += 1;
			print_string("(");
			print_i32(x)
			print_string(", ");
			print_i32(y)
			print_string(")\n");
		}
		y += 1;
		x = 0;
	}
}
