fn main() {
    fn when_odd(x: &mut i32) {
        *x = x * 3 + 1;
    }
    fn when_even(x: &mut i32) {
        *x = x / 2;
    }
    
	print_string("Input number from which to start analysis of 3n+1 problem:\n")
    var x = input_i32();
    while (x != 1) {
        print_i32(x);
        print_string("\n");
        if (x % 2 == 0) {
            when_even
        } else {
            when_odd
        }(&mut x);
    }
}

