fn main() -> i32 {
    var a1 = 1;
    var a2 = 1;
    var b1 = &mut a1; // has mutable reference to a1
    var b2 = &mut a2; // has mutable reference to a2
    var c = if (true) { &mut b1 } else { &mut b2 }; // has mutable reference to b1 and b2
    var d = *c; // (*c) should move out, but fail because it is a reference
    *d
    /*
    but following
    var d = **c; // should be ok
    d
    */
}

/*
so move should happen on the assignment of value (aka transfer in my case)
*/