fn apply(f: Fn(&mut [i32]), row: &mut [i32]) {
	f(row);
}

fn print_row(row: &mut [i32]) {
	var i = 0;
	while (i < length_i32(row)) {
		print_i32(row[i]);
		print_string("\t");
		i += 1;
	}
	print_char('\n');
}

fn insert_row(row: &mut [i32]) {
	var i = 0;
	while (i < length_i32(row)) {
		row[i] = i;
		i += 1;
	}
// }

fn main() {
	var tab = [5;[6;0]];
	var i = 0;
	while (i < 5) {
		apply(insert_row, &mut tab[i], 6);
		i += 1;
	}
	i = 0;
	while (i < 5) {
		apply(print_row, &mut tab[i]);
		i += 1;
	}
}
