fn main() -> i32 {
    var x = 1;
    var y = 2;
    var z = &mut x;
    *(&mut z) = &mut y;
    z
}
/*
Warning: Assignment left: Just 6
Warning: Variables: [
1:         {
            Ident "x": I32
            BorrowedMut 4
            borrows: 
            borrowsMut: 
            lifetime: 0,2,3
        },
2:         {
            Ident "y": I32
            Free
            borrows: 
            borrowsMut: 
            lifetime: 0,2,3
        },
4:         {
            Ident "z": &mut I32
            BorrowedMut 6
            borrows: 
            borrowsMut: 1
            lifetime: 0,2,3
        },
6:         {
            Ident "temporary": &mut I32
            Free
            borrows: 
            borrowsMut: 4
            lifetime: 0,2,3
        }]
Warning: Moving out 6 Identifier (Just (5,5)) (Ident "temporary")
Warning:     Removing mutable borrow of 4
Warning: Ref mut: Just 7
Warning: Variables: [
1:         {
            Ident "x": I32
            BorrowedMut 4
            borrows: 
            borrowsMut: 
            lifetime: 0,2,3
        },
2:         {
            Ident "y": I32
            BorrowedMut 7
            borrows: 
            borrowsMut: 
            lifetime: 0,2,3
        },
4:         {
            Ident "z": &mut I32
            Free
            borrows: 
            borrowsMut: 1
            lifetime: 0,2,3
        },
6:         {
            Ident "temporary": &mut I32
            Moved
            borrows: 
            borrowsMut: 4
            lifetime: 0,2,3
        },
7:         {
            Ident "temporary": &mut I32
            Free
            borrows: 
            borrowsMut: 2
            lifetime: 0,2,3
        }]
Warning: Assignment Right: Just 7
Warning: Transfering 7 to 6
Warning: Variables: [
1:         {
            Ident "x": I32
            BorrowedMut 4
            borrows: 
            borrowsMut: 
            lifetime: 0,2,3
        },
2:         {
            Ident "y": I32
            BorrowedMut 6
            borrows: 
            borrowsMut: 
            lifetime: 0,2,3
        },
4:         {
            Ident "z": &mut I32
            Free
            borrows: 
            borrowsMut: 1
            lifetime: 0,2,3
        },
6:         {
            Ident "temporary": &mut I32
            Free
            borrows: 
            borrowsMut: 2,4
            lifetime: 0,2,3
        },
7:         {
            Ident "temporary": &mut I32
            Moved
            borrows: 
            borrowsMut: 
            lifetime: 0,2,3
        }]
*/